source 'http://rubygems.org'
gem 'rails', '3.0.8'
gem 'mongoid'
gem 'bson_ext'
gem 'jquery-rails'
gem 'sass'
gem 'capistrano'
gem 'wirble'
gem 'resque'
gem 'devise'
gem 'SystemTimer'
gem 'redcarpet'
gem 'exception_notification', :require => 'exception_notifier'
group :test, :development do
   gem 'factory_girl_rails'
end
