development:
  host: localhost
  database: smsflow_development

test:
  host: localhost
  database: smsflow_test

production:
  host: localhost
  port: 27017
  username: smsflow
  password: klsajdaiuoewjrasf
  database: smsflow
